### ISSUE TITLE
I can't seem to get this to work

### ISSUE THREAD

**Issue by malonnnn** [itstake/CHFiles#3]
I am using build #3315 of CommandHelper form builds.enginehub.org

[07:13:52 INFO]: This server is running Paper version git-Paper-1322 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[07:13:52 INFO]: Checking version, please wait...
[07:13:52 INFO]: You are running the latest version

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

Server Type:
Ubuntu 16.04.3 x64
Linode VPS

Now that I've got that out of the way, here's my code:

```
test:/test = >>>
    #No directory gets created, no error. Console prints "Dir Not Exist" every time run command
    if(!is_dir('/home/user/server/plugins/CommandHelper/test/')){
        console('Dir Not Exist')
        create_dir('/home/user/server/plugins/CommandHelper/test/')
    }
    # "File could not be created." every time.
    if(!file_exists('/home/user/server/plugins/CommandHelper/test/test.yml')){
        create_file('/home/user/server/plugins/CommandHelper/test/test.yml')
    }
    write_file('/home/user/server/plugins/CommandHelper/test/test.yml','YMLTEXT','OVERWRITE')
<<<
```

Any ideas?

**Comment by itstake** [comment]
First, use latest version from [here](https://github.com/steakteam/CHFiles/releases)

and I recommand to use relative path(you can access plugins folder using "../")

**Comment by malonnnn** [comment]
Yeah i figured it out, it only has write access to the ./LocalPackages/commands/ folder

but it works great now! thank you!
